### ISSUE TITLE
Exception: (503, '{"title":"Service Unavailable","type":"about:blank","status":503,"detail":"Service Unavailable"}')

### ISSUE THREAD

**Issue by gencharitaci** [puyanoii/Twitter_Search#1]
Hi, I'm getting error. How can I fix it?
```
119022 tweets saved in the file
Exception: (503, '{"title":"Service Unavailable","type":"about:blank","status":503,"detail":"Service Unavailable"}')
```

**Comment by puyanoii** [comment]
Hi there, have you replaced the token with your own Twitter Academic API bearer token?

**Comment by gencharitaci** [comment]
> Hi there, have you replaced the token with your own Twitter Academic API bearer token?

Yes, I replaced it. I tried it many times but I'm getting this error.

**Comment by gencharitaci** [comment]
> > Hi there, have you replaced the token with your own Twitter Academic API bearer token?
> 
> Yes, I replaced it. I tried it many times but I'm getting this error.

I narrowed date range and it's working now.  I'm getting data year by year

**Comment by puyanoii** [comment]
It’s probably worth checking your api status page and see if the request exceed the rate limit:

“503
Service Unavailable
V1.1   V2
The Twitter servers are up, but overloaded with requests. Try again later.
Check the Twitter API status page or the developer community forum in case others are having similar issues, or simply wait and try again later.”

**Comment by gencharitaci** [comment]
> It’s probably worth checking your api status page and see if the request exceed the rate limit:
> 
> “503
> Service Unavailable
> V1.1 V2
> The Twitter servers are up, but overloaded with requests. Try again later.
> Check the Twitter API status page or the developer community forum in case others are having similar issues, or simply wait and try again later.”

Thanks, your work really helped a lot.
